spring:
  application:
    name: course_register_backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course_register
    username: postgres
    password: 123456789
  data:
    mongodb:
      port: 27017
      host: localhost